style.css
Era solo un error de overflow 😅
=> Fix resize editor. 

.gitignore, main.js, package.json
This will add emmet support for html
https://user-images.githubusercontent.com/15637669/129993200-e52d7840-8f63-483d-b9c5-b934ec41a835.mov
=> [✨] feat: emmet support

src/style.css
Resolve problem when we want to add more options on these two sections
=> style: add direction column to sections on aside

index.html, src/style.css
The title bar is displayed when hovering... 🤖
=> feat(Root): tooltip for aside buttons

src/aside.js
Hide and show aside bar on same button click and returns to editor tab
=> feat(Root): hide and show aside bar

package.json, src/skypack.js
=> fix(Root): escape HTML strings for skypack results

src/style.css
=> Fix layout reflow when scrollbar appears

src/style.css
=> Improve the style of the scroll bar

src/skypack.js
=> Skypack: prevent fetching data with same input text

src/utils/editor-hotkeys.js
=> Fix bad open settings action using hotkey

index.html, src/aside.js
closes #73
Thank you for your great labor in the Spanish community.
=> Add autofocus to skypack input

index.html, src/grid.js, src/state.js, src/style.css
Added an option to preserve grid template when page reloads
https://user-images.githubusercontent.com/15878526/135722362-a7ac2484-a924-4921-834e-441df8ab883d.mp4
Added import of styles to create skeleton when page loads (Useful if deploying on http/1.x)
https://user-images.githubusercontent.com/15878526/135378342-06fd6711-7da0-43b8-92c4-5e01b15d7b0b.mp4
=> Grid template preservation & fixed style loading

src/utils/editor-hotkeys.js, src/utils/string.js
=> Add shortcut for copy project url in clipboard

src/style.css
Hi midu,
Thanks for this application.
I fix the cursor hover when you have set de last grid  and move the vertical gutter.
The cursor property must be ***row-resize***
Thanks
=> Fix cursor when you do hover on last-gutter

src/utils/createHtml.js
=> Add most common meta viewport and set charset to UTF-8

src/main.js
This feature allows save code to LocalStorage of your device for maintain it and make it available when browser restart. (Similar to excalidraw.com)
=> Save code in LocalStorage

index.html, src/css/aside.css, src/css/base.css, src/css/editors-layout.css, src/css/settings.css, src/css/skypack.css, src/main.js, src/theme.js
In this pull request I try to make the chosen theme affect the styles of the whole application and not just the text editor. A behaviour more similar to our reference code editor.
I have also taken the opportunity to add the option to choose the Light High Contrast theme. 
Thanks @midudev and all contributors for your great work!
=> Apply global theme selector

index.html, src/css/aside.css, src/css/base.css, src/css/editors-layout.css, src/grid.js, src/sidebar.js, src/theme.js
This code is designed to execute immediately upon script loading. It retrieves the initial state from the browser's local storage and applies these settings to the root element of the HTML document. The goal is to avoid flickering or abrupt changes in the appearance of the web page while it loads.
Before:
After:
=> Fix initial state flickering

index.html, src/aside.js, src/constants/button-actions.js, src/css/history.css, src/events-controller.js, src/history.js, src/main.js, src/style.css
The goal of this Pull Request is to implement Sandboxes History, because it can be a cool feature to add, and also address the open issue #89 in a different way.
https://github.com/midudev/codi.link/assets/84803700/d2e9f575-59d2-4950-8034-da197c330b37
=> History management feature

index.html, src/constants/initial-settings.js, src/editor.js
Two new settings based on VSCode editor settings.
=> feat: add cursor blinking and caret animation settings

src/style.css
❗Source of bug/
Mobile browsers have a toolbar that obscures or mis-renders web content.
✅Solution
The dvh(Dynamic viewport heigth) unit of measure was added to the body to fix this problem since this measure subtracts the size of the toolbar achieving a better rendering of the content and showing the buttons correctly.
---
Before
<div>
Chrome view
Firefox view
</div>
After
<div>
Chrome view
Firefox view
</div>
=> Fix: bad rendering of buttons on phone
