debounce.js
main.js

Prevents instant updates (reduces flickering #18) when user types fast.

feat: debounce update call

---

main.js

Issue #28
Added a line in monaco editor settings. This allows the widgets belonging to each editor to be positioned with a fixed and in case of overflowing they overlap on other editors and elements

Fixed monaco widget overflow

---

src/skypack.js

Fixed bug when importing packages with the following name **@owner/package-name**

fix(Root): name error when importing if package has user scope

---

index.html

- Remove last dot in font ligatures description.
- Some style refactor (trim spaces and put the svg in online line, like the others)

fix typo in font ligatures description

---

index.html
package.json
src/aside.js
src/download.js
src/events-controller.js
src/main.js
src/skypack.js

- Add an event emitter, because we need to communicate in a better way than ```window.postMessage```, so the skypack part was refactorized before implement the download button feature. 
- Add a download button in the aside bar. This button don't open a panel, so we need to do some refactor in the ```aside.js``` file.
- Add a download functionality with this default settings: ```zipInSingleFile=false``` and ```fileName=codi.link```
- All download config options has been tested, but there are not exposed to the app yet (maybe in next iterations?)
- Use the vscode official icon (optimized via svg omg ;) ): https://github.com/microsoft/vscode-icons/blob/main/icons/dark/file-zip.svg
- I have used the code part of ```generateAsync``` from the old PR of @rdmarcos49. Thanks!
ISSUES CLOSED: #19

Add support to download the user code via zip button 

---

src/settings.js

Before (If you write the font size value, you need to do click out to see the changes):
Now:

Update font size without "focusout"

---

index.html
src/style.css

fix(Root): Fix correct flow in fields elements in aside of settings panel

---

src/editor.js

Default worker now points to editor worker

fix(Root): Fix console worker warnings

---

src/events-controller.js
src/skypack.js

Usually you want to import a dependency which is not a JavaScript file but CSS. In that case if you click the package you end up with this for example (using normalize.css):
For those cases, this PR adds a button to copy the package URL to the clipboard so you can paste it into a `link` tag, an `@import` on the CSS, or even a dynamic `import()` on the JavaScript.
I also made that in the import name the dots are replaced by underscores.

Add copy button on skypack packages

---

index.html
src/main.js
src/settings.js
src/style.css
src/utils/dom.js

This PR changes the code of the settings to use native form APIs.
- Use a form element to wrap the settings form.
- Replace the custom `data-for` attribute with native `name` attribute for naming form controls.
- Use event delegation by attaching listeners to `input` and `change` events to the form element itself.
- Use `radio` inputs for the layout settings instead of attaching click listeners to the LayoutPreview elements. Hence there is no need for using a different way to retrieve that setting with the click event.
This changes results in more cleaner and maintainable code by using the standard API for handling forms.

Use an HTML form for settings

---

src/main.js
src/utils/createHtml.js

This solves #185
With this change, anytime the user writes changes to the CSS, the content of the style tag is updated directly instead of changing the `srcdoc`. This way the iframe document doesn't reload and any Javascript state is retained.
The behavior retains the same when the user changes the JavaScript or the HTML.
This PR is open to reviews, opinions and suggestions for improvement. Please tell me if there is any edge case where this doesn't work.

Support editing CSS without reloading preview

---

package.json
src/events-controller.js

Replace the eventBus inplementation to use the native EventTarget API
instead of a third party library.

Use native EventTarget instead of mitt

---

index.html
src/constants/initial-settings.js
src/main.js
src/sidebar.js
src/style.css

I think that the sidebar and its icons are very large, so I have added the option to make it compact to have more space available in the editor.
Apart from "compact", it allows the possibility of adding new options in the future by other users, such as "hidden" to hide the sidebar (or make a much thinner bar without icons) and only show it when placing the cursor on the left side of the screen or clicking in it (just a idea).
This is my first contribution to a public project and I'm not sure if I did it the right way, so anyone can feel free to suggest any changes.

Feat: add option to change sidebar size

---

src/grid.js
src/settings.js

- The gutters value was being set incorrectly.
- Move the logic of obtaining grid configs to the grid.js file instead of the settings.js
- Store only the layout name on the state.
closes: #195

Fix layout resizing

---

src/css/notifications.css

Set Headway changelog badge to 20px

---

src/components/codi-editor/CodiEditor.styles.js

This makes easier to see the code below the icons

Icons transparent on editor hover or focus

---

index.html

Había un "setting- item" sin las correspondientes etiquetas de cierre, lo que provocaba que no se viese los estilos correctamente.

fix: Added missing closing tags in Settings item

---

index.html
src/aside.js
src/console-script.js
src/console.js
src/constants/button-actions.js
src/constants/console-icons.js
src/css/console.css
src/main.js
src/style.css
src/utils/WindowPreviewer.js
src/utils/createHtml.js

This pull request adds console functionality to the application, allowing users to log, warn, info, and error messages. It also includes the necessary CSS and JavaScript changes to support the console feature.

Add console functionality to the application

---

src/main.js

En algunos navegadores el caracter "|" no se encodea por lo que al intentar hacer el split de la ruta esta genera errores que no permiten una correcta renderizacion del css y js

Determinar dinámicamente el delimitador en el nombre de la ruta

---

src/aside.js
src/components/codi-editor/extensions/editor-hotkeys.js

Fixed a bug in the copy URL action that added an additional slash to the URL, making HTML buggy.
Original:
Opening link after copying link with button or action:
Change the copy actions to copy the actual location, enabling functionality even when on localhost.

Fix: Duplicated slash at copy button & shortcut

---

src/console.js

feat: console output spacing

---

src/css/base.css
src/css/console.css

No CSS properties where define for the colors on the console, rendering logs with low contrasts on light themes. Added custom properties con base and console css files

Add color variants to improve usability on lighter themes

---

src/css/editors-layout.css
src/grid.js

Hola! 👋
Esta es mi primer Pull Request en GitHub! 😅
Codi.link es excelente, pero al cambiar el tamaño de los editores utilizando el drag a veces ocurre un bug que contrae los demás editores aleatoriamente, lo cual es bastante molesto.
Demo del error con un [video de Midu 😎](https://www.youtube.com/watch?v=iTjkiI8QQsM)
[Video](https://github.com/user-attachments/assets/e195b70c-8e23-4c4c-afcf-0aaf62ca93fe)
Creo que este error se genera cuando uno de los editores o "tracks" se contrae por completo. La dependencia de split-grid le asigna un fraction con valor de 0.
Después cuando la dependencia intenta calcular nuevamente el valor de los fraction (realiza una división) al tener un valor de 0 esto genera que los fraction restantes tomen valores muy elevados. Ahí es cuando el layout se rompe y …

Fix Fraction Explosion

---

src/css/editors-layout.css
src/grid.js

Solución de este bug que contrae las cuadrículas del grid:
https://github.com/user-attachments/assets/4a2e1e27-56db-4715-b107-d4e66826aef9
También le agregué con CSS un píxel de sombra al gutter en cada costado para poder desplazarlo al máximo.
Configuré el tamaño mínimo en 300px para el editor, es un poco más de lo que ocupa el min-content del selector de pestañas. Si les parece poco o mucho, se puede cambiar fácilmente modificando esa línea del JS.

Fix fraction calculation in tabs layout

---

src/drag-file.js

This pull request includes an update to `src/drag-file.js` to enhance the user experience when interacting with the drag-and-drop file overlay.
* [`src/drag-file.js`](diffhunk://#diff-fc762f816a54848c5699896a1f510c933b39fd3910bec24e44b41b8b968e9635R34-R39): Added a `visibilitychange` event listener to hide the drag overlay when the document becomes hidden.
When the user drop something that is not a file and the browser launch a new tab, the overlay doesn not hide because the `dragleave` event is not being called.
That behavior happens with dropped links, emails (from the Apple mail app), files from VSCode (because they are drop as a string with the route), and possibly many more.
Before the change:
https://github.com/user-attachments/assets/bfdf08c8-1345-4a1e-aa90-a0442475fe5c
After the …

fix: error when dragging something that is not a file

---

src/components/codi-editor/CodiEditor.styles.js
src/css/aside.css
src/style.css

This pull request includes two updates to enhance the user experience:
1. Adjusted z-index values to prevent overlap with aside panels.
2. Replaced vh with dvh for better handling of viewport height on mobile devices, particularly to account for dynamic browser UI elements.
| Before | After |
| ---------- | ------- |
| ![image](https://github.com/user-attachments/assets/6eab3c53-3e2a-449f-89c0-5a4f65ad5a20) | ![image](https://github.com/user-attachments/assets/c0ce0a05-1772-48c6-a736-caf660e060db) |

Fix mobile UI

---

src/console.js

Actualmente, al hacer `console.log` de un **template string multilínea** que contiene **etiquetas XML o HTML**, el contenido se procesa de manera inesperada:
- Las **etiquetas desaparecen**, dejando solo el contenido interno.
- Si es HTML válido, la consola puede **renderizar** ese HTML, lo que genera resultados inesperados (por ejemplo, textos en **negrita** si son etiquetas `<h1>`, `<h2>`, etc).
- En cambio, si el template está en una **sola línea**, se muestra correctamente como string.
---
Con el ajuste que propongo:
- Se asegura que **siempre** se imprima el contenido **literal** del string, incluyendo todas las etiquetas XML/HTML, sin que el navegador intente interpretarlas o renderizarlas.
- Esto es útil para debuggear templates, peticiones XML, estructuras HTML, etc.
--- …

Fix: Evitar que console.log renderice HTML/XML en templates multilínea
